import React from 'react'
import Header from '../components/Header'
import LeftSideBar from '../components/LeftSideBar'
import { FaUserCircle, FaPhoneSquare } from 'react-icons/fa'
import { MdEmail } from 'react-icons/md'
import Link from 'next/link'
import Head from 'next/head'

const page = () => {
  return (
    <>
      <Head>
        <title>View-Eye || Contact Us</title>
        <meta name="description" content="Generated by View-Eye" />
      </Head>
      <Header />
      <div className="main-box flex relative">
        <LeftSideBar />
        <div className="contact-us-page relative top-14 left-12 ml-5 mt-3">
          <h1 className='text-6xl text-center'>Contact us!</h1>

          <div className="conatectPageMainContent-Box flex w-full items-start flex-wrap">

            <div className="contactFormBox">
              <form className="ContactForm-cotainer">
                <div className="firstNameBox-CForm grid text-start items-center">
                  <label htmlFor="fname">First Name: </label>
                  <div className='flex items-center relative'>
                    <b className='text-3xl absolute left-2 flex items-center'><FaUserCircle /><b className='text-lg font-normal ml-1'>|</b></b>
                    <input type="text" id='fname' name='firstname' className='pl-12 pr-4 h-12 w-96 border-2 outline-0 rounded-lg py-2 text-xl font-semibold' required />
                  </div>
                </div>
                <div className="lastNameBox-CForm grid text-start items-center">
                  <label htmlFor="lname">Last Name: </label>
                  <div className='flex items-center'>
                    <b className='text-3xl absolute left-2 flex items-center'><FaUserCircle /><b className='text-lg font-normal ml-1'>|</b></b>
                    <input type="text" id='lname' name='lastname' className='pl-12 pr-4 h-12 w-96 border-2 outline-0 rounded-lg px-3 py-2 text-xl font-semibold' required />
                  </div>
                </div>
                <div className="emailBox-CForm grid text-start items-center">
                  <label htmlFor="email">E-mail: </label>
                  <div className='flex items-center'>
                    <b className='text-3xl absolute left-2 flex items-center'><MdEmail /><b className='text-lg font-normal ml-1'>|</b></b>
                    <input type="text" id='email' name='email' className='pl-12 pr-4 h-12 w-96 border-2 outline-0 rounded-lg px-3 py-2 text-xl font-semibold' required />
                  </div>
                </div>
                <div className="messageBox-CForm grid text-start items-center">
                  <label htmlFor="message">Message: </label>
                  <textarea name="message" id="message" required cols={30} rows={10} className='resize-none border-2 outline-0 rounded-lg px-4 py-4 h-52 w-96'></textarea>
                </div>
                <div className="submitBtn grid items-center justify-center">
                  <button type='submit' className="text-xl font-semibold px-3 py-2 my-2 rounded-lg bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-30% to-emerald-500 to-90% ">Contact</button>
                </div>
              </form>
            </div>

            <div className="otherContectInfo w-3/5 px-11 flex-wrap">

              <div className="otherContect flex items-center justify-between flex-wrap">
                <div className="ContectDetailWithNumber contectHover h-48 w-72 flex items-center justify-center border-2 rounded-xl transition duration-1000 ease-in-out my-3 mr-2">
                  <div className="contectNumber-Address-Box w-60 grid items-center justify-center px-4 py-4">
                    <div className="number-Box flex items-center justify-between w-56 border-b-2 py-2">
                      <b className="numberPhone-tel">Phone: 03257390045</b><b className='tel-phone-ico'><Link href="tel:03257390045" title='Call Now' className='text-4xl'><FaPhoneSquare /></Link></b>
                    </div>
                    <div className="address-Box text-justify m-0 mt-2">
                      <b className='text-justify'>Address:</b><code> Bhutta No: 01, Street No 3, Bahawalpur, Punjab, Pakistan</code>
                    </div>
                  </div>
                </div>

                <div className="contectDetailWithEmailAndManagerMail contectHover border-2 text-lg grid items-center justify-center py-8 px-8 rounded-lg w-72 content-center justify-items-center h-48">
                  <div className="ceoMAILbOX w-52 grid justify-center justify-items-center items-center h-14">
                    <b>CEO: </b> <code>hasaanad12min@gmail.com</code>
                  </div>
                  <div className="managerMailBox w-52 grid justify-center justify-items-center items-center h-14">
                    <b>Manager: </b> <code>shoaibabbas7671@gmail.com</code>
                  </div>
                  <div className="companyMailBox w-52 grid justify-center justify-items-center items-center h-14">
                    <b>Company: </b> <code>eyeview@gmail.com</code>
                  </div>
                </div>
              </div>

              <div className="contectDetailWithMaps">
                <div className="mapView">
                  <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11495.111628267881!2d71.6792006!3d29.4087025!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e1!3m2!1sen!2s!4v1685354968054!5m2!1sen!2s" width="680" height="250" style={{ border: "0" }} className='rounded-lg'></iframe>
                </div>
              </div>

            </div>

          </div>

        </div>
      </div>
    </>
  )
}

export default page
