import React from 'react'
import Header from '../components/Header'
import LeftSideBar from '../components/LeftSideBar'
import illustrateAbout from '@/../public/img/about.svg'
import Image from 'next/image'
import Head from 'next/head'

const page = () => {
  return (
    <>
      <Head>
        <title>View-Eye || About</title>
        <meta name="description" content="Generated by View-Eye" />
      </Head>
      <Header />
      <div className="main-box flex relative">
        <LeftSideBar />
        <div className="aboutMainContent ml-3">
          <div className="illustratePic">
            <div className="ImageBox">
              <Image src={illustrateAbout} alt='illustrate-pic' />
            </div>
          </div>
          <h1 className='text-6xl text-center font-semibold my-4'>Welcome To View-Eye</h1>
          <p className='text-center'>View-Eye is a Professional Commerce, Tech, Education & Entertainment Platform. Here we will provide you only interesting content, which you will like very much. We{"'"}re dedicated to providing you the best of Commerce, Tech, Education & Entertainment, with a focus on dependability and Online . We{"'"}re working to turn our passion for Commerce, Tech, Education & Entertainment into a booming online website. We hope you enjoy our Commerce, Tech, Education & Entertainment as much as we enjoy offering them to you.</p><br />
          <p className='text-center'>I will keep posting more important posts on my Website for all of you. Please give your support and love.</p>
          <h2 className='text-center text-red-600 font-semibold my-4'>Thanks For Visiting Our Site</h2>
          <h3 className='text-center text-blue-800 font-semibold my-4'>Have a nice day!</h3>
        </div>
      </div>
    </>
  )
}

export default page
